-- ==========================================
-- Society Maintenance Tracker — Complete Schema
-- ==========================================

-- 1. CUSTOM TYPES / ENUMS
CREATE TYPE public.app_role AS ENUM ('resident', 'admin');

CREATE TYPE public.complaint_category AS ENUM (
  'plumbing', 'electrical', 'structural', 'pest_control',
  'elevator', 'parking', 'security', 'cleaning', 'other'
);

CREATE TYPE public.complaint_status AS ENUM ('open', 'in_progress', 'resolved');

CREATE TYPE public.complaint_priority AS ENUM ('low', 'medium', 'high');

-- 2. TABLES

-- Profiles (extended user info)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  apartment_no TEXT NOT NULL,
  phone TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User Roles (RBAC)
CREATE TABLE public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL DEFAULT 'resident',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT user_roles_user_id_key UNIQUE (user_id)
);

-- Complaints
CREATE TABLE public.complaints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resident_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  category public.complaint_category NOT NULL,
  description TEXT NOT NULL,
  status public.complaint_status NOT NULL DEFAULT 'open',
  priority public.complaint_priority NOT NULL DEFAULT 'medium',
  is_overdue BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ NULL
);

-- Complaint History (Append-only Audit Trail)
CREATE TABLE public.complaint_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_id UUID NOT NULL REFERENCES public.complaints(id) ON DELETE CASCADE,
  changed_by UUID NOT NULL REFERENCES public.profiles(id),
  old_status public.complaint_status NULL,
  new_status public.complaint_status NULL,
  old_priority public.complaint_priority NULL,
  new_priority public.complaint_priority NULL,
  note TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Complaint Photos
CREATE TABLE public.complaint_photos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_id UUID NOT NULL REFERENCES public.complaints(id) ON DELETE CASCADE,
  storage_path TEXT NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Notices
CREATE TABLE public.notices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  is_important BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- App Settings (Configurable Overdue Threshold)
CREATE TABLE public.app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. INDEXES FOR PERFORMANCE
CREATE INDEX idx_complaints_resident_id ON public.complaints(resident_id);
CREATE INDEX idx_complaints_status ON public.complaints(status);
CREATE INDEX idx_complaints_category ON public.complaints(category);
CREATE INDEX idx_complaints_priority ON public.complaints(priority);
CREATE INDEX idx_complaints_created_at ON public.complaints(created_at);
CREATE INDEX idx_complaints_is_overdue ON public.complaints(is_overdue);
CREATE INDEX idx_complaint_history_complaint_id ON public.complaint_history(complaint_id);
CREATE INDEX idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX idx_notices_is_important ON public.notices(is_important, created_at DESC);

-- 4. DEFAULT SETTINGS SEED
INSERT INTO public.app_settings (key, value)
VALUES ('overdue_threshold_days', '7')
ON CONFLICT (key) DO NOTHING;

-- 5. TRIGGER FUNCTIONS

-- Auto create profile & user_role on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, apartment_no, phone)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'Resident'),
    COALESCE(NEW.raw_user_meta_data->>'apartment_no', 'N/A'),
    COALESCE(NEW.raw_user_meta_data->>'phone', 'N/A')
  );

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'resident');

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Auto-confirm user email upon registration
CREATE OR REPLACE FUNCTION public.auto_confirm_user()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.email_confirmed_at IS NULL THEN
    NEW.email_confirmed_at = NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created_auto_confirm
  BEFORE INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.auto_confirm_user();

-- Trigger function: Update timestamp on complaints
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_complaints_updated_at
  BEFORE UPDATE ON public.complaints
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER update_notices_updated_at
  BEFORE UPDATE ON public.notices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Trigger function: Handle resolved_at timestamp
CREATE OR REPLACE FUNCTION public.handle_complaint_resolved_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'resolved' AND (OLD.status IS NULL OR OLD.status != 'resolved') THEN
    NEW.resolved_at = NOW();
    NEW.is_overdue = FALSE; -- Resolved items are never overdue
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_complaint_resolved_at
  BEFORE UPDATE ON public.complaints
  FOR EACH ROW EXECUTE FUNCTION public.handle_complaint_resolved_at();

-- Function: Overdue Checker (can be invoked by CRON or API trigger)
CREATE OR REPLACE FUNCTION public.check_overdue_complaints()
RETURNS VOID AS $$
DECLARE
  threshold_days INT := 7;
BEGIN
  SELECT COALESCE(value::INT, 7) INTO threshold_days
  FROM public.app_settings
  WHERE key = 'overdue_threshold_days';

  UPDATE public.complaints
  SET is_overdue = TRUE
  WHERE status IN ('open', 'in_progress')
    AND created_at < (NOW() - (threshold_days || ' days')::INTERVAL)
    AND is_overdue = FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. CUSTOM ACCESS TOKEN HOOK FOR SUPABASE AUTH JWT
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb AS $$
DECLARE
  claims jsonb;
  user_role public.app_role;
BEGIN
  SELECT role INTO user_role FROM public.user_roles
  WHERE user_id = (event->>'user_id')::uuid;

  claims := event->'claims';
  claims := jsonb_set(claims, '{user_role}', to_jsonb(COALESCE(user_role, 'resident')));
  event := jsonb_set(event, '{claims}', claims);
  RETURN event;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM authenticated, anon, public;

-- 7. ROW LEVEL SECURITY (RLS) POLICIES

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaint_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaint_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Helper function to check if user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- PROFILES POLICIES
CREATE POLICY "Users can view own profile or admins view all"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id OR public.is_admin());

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- USER ROLES POLICIES
CREATE POLICY "Users can view own role or admins view all"
  ON public.user_roles FOR SELECT
  USING (user_id = auth.uid() OR public.is_admin());

-- COMPLAINTS POLICIES
CREATE POLICY "Residents view own complaints or admins view all"
  ON public.complaints FOR SELECT
  USING (resident_id = auth.uid() OR public.is_admin());

CREATE POLICY "Residents can create complaints"
  ON public.complaints FOR INSERT
  WITH CHECK (auth.uid() = resident_id);

CREATE POLICY "Admins can update complaints"
  ON public.complaints FOR UPDATE
  USING (public.is_admin());

-- COMPLAINT HISTORY POLICIES
CREATE POLICY "Users view history of visible complaints"
  ON public.complaint_history FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.complaints c
      WHERE c.id = complaint_id AND (c.resident_id = auth.uid() OR public.is_admin())
    )
  );

CREATE POLICY "Authenticated users can insert history on accessible complaints"
  ON public.complaint_history FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- COMPLAINT PHOTOS POLICIES
CREATE POLICY "Users view photos of visible complaints"
  ON public.complaint_photos FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.complaints c
      WHERE c.id = complaint_id AND (c.resident_id = auth.uid() OR public.is_admin())
    )
  );

CREATE POLICY "Residents can insert photos for own complaints"
  ON public.complaint_photos FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.complaints c
      WHERE c.id = complaint_id AND c.resident_id = auth.uid()
    )
  );

-- NOTICES POLICIES
CREATE POLICY "Authenticated users can view notices"
  ON public.notices FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can manage notices"
  ON public.notices FOR ALL
  USING (public.is_admin());

-- APP SETTINGS POLICIES
CREATE POLICY "Admins can view and manage app settings"
  ON public.app_settings FOR ALL
  USING (public.is_admin());

-- 8. STORAGE BUCKET SETUP
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'complaint-photos',
  'complaint-photos',
  false,
  5242880, -- 5MB
  ARRAY['image/jpeg', 'image/png', 'image/webp']
) ON CONFLICT (id) DO NOTHING;

-- Storage RLS
CREATE POLICY "Complaint photos upload policy"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'complaint-photos');

CREATE POLICY "Complaint photos select policy"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'complaint-photos');

CREATE POLICY "Complaint photos delete policy"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'complaint-photos' AND public.is_admin());
